//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Psyia : Valve.VR.SteamVR_ActionSet
    {
        
        public SteamVR_Input_ActionSet_Psyia_In inActions;
        
        public SteamVR_Input_ActionSet_Psyia_Out outActions;
    }
}
