//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Psyia : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Single ApplyForce
        {
            get
            {
                return SteamVR_Actions.psyia_ApplyForce;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.psyia_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.psyia_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.psyia_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Single SpawnParticles
        {
            get
            {
                return SteamVR_Actions.psyia_SpawnParticles;
            }
        }
        
        public virtual SteamVR_Action_Boolean ToggleMenu
        {
            get
            {
                return SteamVR_Actions.psyia_ToggleMenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean SlowTime
        {
            get
            {
                return SteamVR_Actions.psyia_SlowTime;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.psyia_Haptic;
            }
        }
    }
}
